name: Update Directory Structure
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: application.properties
        env:
          username:admin
          password:mysqlmysql
        run: |
          echo $username
          echo $password
